# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(default='Images/No-img.jpg', null=True, upload_to='Images/'),
        ),
    ]
